name: Build & Deploy to Azure Static Web Apps (Blazor WASM)

on:
  push: { branches: [ main ] }
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # KHÔNG có Functions => bỏ api_location
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_SKY_0E58D3F10 }}
          app_location: "MHT_GWP/Mht_GWP"   # thư mục chứa Mht_GWP.csproj
          output_location: "wwwroot" 

